- name: Creates directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copy Docker Compose File
  copy:
    src: "{{ docker_compose_local_path }}"
    dest: "{{ docker_compose_remote_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copy Environment File
  copy:
    src: "{{ docker_compose_environment_local_path }}"
    dest: "{{ docker_compose_environment_remote_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Authenticate to GitHub Container Registry
  shell: |
    echo "{{ github_token }}" | docker login ghcr.io -u verovec --password-stdin
  args:
    executable: /bin/bash

- name: Pull Image and Start Services with Docker Compose
  shell: |
    cd /home/{{ ansible_user }}
    docker-compose pull
    docker-compose up -d --no-deps --build
    docker image prune -f
  args:
    executable: /bin/bash
