version: '3.9'

services:
  webapp:
    container_name: webapp
    restart: always
    image: ghcr.io/verovec/svp-application:latest
    # volumes:
    #   - .:/app
    ports:
      - "8000:80"
    env_file:
      - production.env
    depends_on:
      - mysql
    networks:
      - web-net

#   web2:
#     container_name: web2
#     restart: always
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#     ports:
#       - "8001:80"
#     env_file:
#       - dev.env
#     depends_on:
#       - mysql
#     networks:
#       - web-net

  mysql:
    container_name: mysql
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: default_user
      MYSQL_PASSWORD: default_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - web-net

volumes:
  mysql_data:

networks:
  web-net:
    driver: bridge
